name: .NET Framework (Mono)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building Program Overflow
      run: msbuild -p:Configuration=Release -p:Platform="Any CPU"